<?php
/**
 * Airspace
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open Aviation Data
 *
 * Accessible Aviation Data for the Masses
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * Airspace Class Doc Comment
 *
 * @category    Class */
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Airspace implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Airspace';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'name' => 'string',
        'base_ft' => 'int',
        'ceil_ft' => 'int',
        'ceil_ref' => 'string',
        'polygon' => '\Swagger\Client\Model\Polygon[]'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'base_ft' => 'base_ft',
        'ceil_ft' => 'ceil_ft',
        'ceil_ref' => 'ceil_ref',
        'polygon' => 'polygon'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'base_ft' => 'setBaseFt',
        'ceil_ft' => 'setCeilFt',
        'ceil_ref' => 'setCeilRef',
        'polygon' => 'setPolygon'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'base_ft' => 'getBaseFt',
        'ceil_ft' => 'getCeilFt',
        'ceil_ref' => 'getCeilRef',
        'polygon' => 'getPolygon'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['base_ft'] = isset($data['base_ft']) ? $data['base_ft'] : null;
        $this->container['ceil_ft'] = isset($data['ceil_ft']) ? $data['ceil_ft'] : null;
        $this->container['ceil_ref'] = isset($data['ceil_ref']) ? $data['ceil_ref'] : null;
        $this->container['polygon'] = isset($data['polygon']) ? $data['polygon'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name Airspace Name.
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets base_ft
     * @return int
     */
    public function getBaseFt()
    {
        return $this->container['base_ft'];
    }

    /**
     * Sets base_ft
     * @param int $base_ft Base elevation of airspace (MSL).
     * @return $this
     */
    public function setBaseFt($base_ft)
    {
        $this->container['base_ft'] = $base_ft;

        return $this;
    }

    /**
     * Gets ceil_ft
     * @return int
     */
    public function getCeilFt()
    {
        return $this->container['ceil_ft'];
    }

    /**
     * Sets ceil_ft
     * @param int $ceil_ft Ceiling elevation of airspace.
     * @return $this
     */
    public function setCeilFt($ceil_ft)
    {
        $this->container['ceil_ft'] = $ceil_ft;

        return $this;
    }

    /**
     * Gets ceil_ref
     * @return string
     */
    public function getCeilRef()
    {
        return $this->container['ceil_ref'];
    }

    /**
     * Sets ceil_ref
     * @param string $ceil_ref Ceiling elevation measurement type (AGL or MSL).
     * @return $this
     */
    public function setCeilRef($ceil_ref)
    {
        $this->container['ceil_ref'] = $ceil_ref;

        return $this;
    }

    /**
     * Gets polygon
     * @return \Swagger\Client\Model\Polygon[]
     */
    public function getPolygon()
    {
        return $this->container['polygon'];
    }

    /**
     * Sets polygon
     * @param \Swagger\Client\Model\Polygon[] $polygon
     * @return $this
     */
    public function setPolygon($polygon)
    {
        $this->container['polygon'] = $polygon;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}
