<?php
/**
 * Turbulence
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open Aviation Data
 *
 * Accessible Aviation Data for the Masses
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * Turbulence Class Doc Comment
 *
 * @category    Class */
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Turbulence implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Turbulence';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'turbulence_intensity' => 'string',
        'turbulence_min_alt_ft_agl' => 'int',
        'turbulence_max_alt_ft_agl' => 'int'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'turbulence_intensity' => 'turbulence_intensity',
        'turbulence_min_alt_ft_agl' => 'turbulence_min_alt_ft_agl',
        'turbulence_max_alt_ft_agl' => 'turbulence_max_alt_ft_agl'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'turbulence_intensity' => 'setTurbulenceIntensity',
        'turbulence_min_alt_ft_agl' => 'setTurbulenceMinAltFtAgl',
        'turbulence_max_alt_ft_agl' => 'setTurbulenceMaxAltFtAgl'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'turbulence_intensity' => 'getTurbulenceIntensity',
        'turbulence_min_alt_ft_agl' => 'getTurbulenceMinAltFtAgl',
        'turbulence_max_alt_ft_agl' => 'getTurbulenceMaxAltFtAgl'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['turbulence_intensity'] = isset($data['turbulence_intensity']) ? $data['turbulence_intensity'] : null;
        $this->container['turbulence_min_alt_ft_agl'] = isset($data['turbulence_min_alt_ft_agl']) ? $data['turbulence_min_alt_ft_agl'] : null;
        $this->container['turbulence_max_alt_ft_agl'] = isset($data['turbulence_max_alt_ft_agl']) ? $data['turbulence_max_alt_ft_agl'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets turbulence_intensity
     * @return string
     */
    public function getTurbulenceIntensity()
    {
        return $this->container['turbulence_intensity'];
    }

    /**
     * Sets turbulence_intensity
     * @param string $turbulence_intensity Turbulence intensity values (0-9)
     * @return $this
     */
    public function setTurbulenceIntensity($turbulence_intensity)
    {
        $this->container['turbulence_intensity'] = $turbulence_intensity;

        return $this;
    }

    /**
     * Gets turbulence_min_alt_ft_agl
     * @return int
     */
    public function getTurbulenceMinAltFtAgl()
    {
        return $this->container['turbulence_min_alt_ft_agl'];
    }

    /**
     * Sets turbulence_min_alt_ft_agl
     * @param int $turbulence_min_alt_ft_agl Minimum altitude for turbulence (ft AGL)
     * @return $this
     */
    public function setTurbulenceMinAltFtAgl($turbulence_min_alt_ft_agl)
    {
        $this->container['turbulence_min_alt_ft_agl'] = $turbulence_min_alt_ft_agl;

        return $this;
    }

    /**
     * Gets turbulence_max_alt_ft_agl
     * @return int
     */
    public function getTurbulenceMaxAltFtAgl()
    {
        return $this->container['turbulence_max_alt_ft_agl'];
    }

    /**
     * Sets turbulence_max_alt_ft_agl
     * @param int $turbulence_max_alt_ft_agl Maximum altitude for turbulence (ft AGL)
     * @return $this
     */
    public function setTurbulenceMaxAltFtAgl($turbulence_max_alt_ft_agl)
    {
        $this->container['turbulence_max_alt_ft_agl'] = $turbulence_max_alt_ft_agl;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}
