<?php
/**
 * TAFForecastsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open Aviation Data
 *
 * Accessible Aviation Data for the Masses
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TAFForecastsTest Class Doc Comment
 *
 * @category    Class */
// * @description TAFForecasts
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TAFForecastsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "TAFForecasts"
     */
    public function testTAFForecasts()
    {

    }

    /**
     * Test attribute "valid"
     */
    public function testPropertyValid()
    {

    }

    /**
     * Test attribute "indicator"
     */
    public function testPropertyIndicator()
    {

    }

    /**
     * Test attribute "becoming"
     */
    public function testPropertyBecoming()
    {

    }

    /**
     * Test attribute "probability"
     */
    public function testPropertyProbability()
    {

    }

    /**
     * Test attribute "wind"
     */
    public function testPropertyWind()
    {

    }

    /**
     * Test attribute "visibility"
     */
    public function testPropertyVisibility()
    {

    }

    /**
     * Test attribute "altimeter"
     */
    public function testPropertyAltimeter()
    {

    }

    /**
     * Test attribute "wx_string"
     */
    public function testPropertyWxString()
    {

    }

    /**
     * Test attribute "no_decoded"
     */
    public function testPropertyNoDecoded()
    {

    }

    /**
     * Test attribute "sky"
     */
    public function testPropertySky()
    {

    }

    /**
     * Test attribute "turbulence"
     */
    public function testPropertyTurbulence()
    {

    }

    /**
     * Test attribute "icing"
     */
    public function testPropertyIcing()
    {

    }

    /**
     * Test attribute "tmp"
     */
    public function testPropertyTmp()
    {

    }

}
